### ISSUE TITLE
Put the libspotify cache folder in .cache

### ISSUE THREAD

**Issue by raoulh** [catharsis/spotifile#17]
The libspotify cache folder is saved in .config/spotifile/libspotify

It should be saved in .cache/spotifile/libspotify instead.

**Comment by catharsis** [comment]
Hm, on second thought, that should already be the case. We use https://developer.gnome.org/glib/unstable/glib-Miscellaneous-Utility-Functions.html#g-get-user-cache-dir to decide where to put the cache. This should be resolved to XDG_CACHE_HOME if it's set, and default to ~/.cache otherwise.

On my machine, it's indeed put in ~/.cache/spotifile/libspotify.

Is XDG_CACHE_HOME set in your session?

**Comment by raoulh** [comment]
hmm, ok. That was the problem, XDG_CACHE_HOME was wrong. Thanks
