### ISSUE TITLE
Option to select prefered bitrate

### ISSUE THREAD

**Issue by raoulh** [catharsis/spotifile#20]
An option in config file to choose the bitrate you want from spotify would be nice to have. Libspotify has an API for that:

```
sp_error sp_session_preferred_bitrate(sp_session *session, sp_bitrate bitrate)
```

**Comment by catharsis** [comment]
Absolutely, that's on the list-of-things-to-add which only exists in my head; and now it's here as well. The way I imagine it you'd have a directory containing user specific settings, with writable files for each setting. Writing to them would update the setting.

Of course, that would require implementing write-support, which is something I've managed to avoid so far.

**Comment by raoulh** [comment]
That may be nice, but a bit overkill don't you think ? :)
A simple option in the already existing config file is way much easier :)

**Comment by catharsis** [comment]
That's true, but from a "purity" perspective I like the idea of keeping (non-sensitive) spotify-data accessible and eventually editable from within the file-system itself.

Of course, that doesn't necessarily exclude the possibility to allow configuration from the config file itself as well, though that makes the matter a bit more complex, since it would effectively overwrite the user's preferences without user interaction (since there's no "Apply changes" analogue) if you don't also allow spotifile to update the configuration file with current values - and that's something I would rather avoid if at all possible. Does that make sense?

**Comment by catharsis** [comment]
This is now implemented, so I'm closing this. There is still the matter of documenting the feature, though - but I'm gonna add a new issue for that.
